version: '3.8'

services:
  todo-db:
    image: postgres
    container_name: growdev-db-dev
    volumes:
      - todo-data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo

  todo-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: todo-api-dev
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://todo:todo@todo-db:5432/todo
    depends_on:
      - todo-db
    volumes:
      - .:/app

networks:
  default:
    name: growdev

volumes:
  todo-data:
