version: "3.6"

services:
  todo-db:
    image: postgres:14
    container_name: growdev-db-prod
    volumes:
      - todo-data-prod:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo

  todo-redis:
    image: bitnami/redis:7.0.7
    container_name: growdev-redis-prod
    environment:
      - REDIS_PASSWORD=todo
    ports:
      - 6379:6379

  todo-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: todo-api-prod
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://todo:todo@todo-db:5432/todo
      - REDIS_HOST=todo-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=todo

    depends_on:
      - todo-redis
      - todo-db
    volumes:
      - .:/app

volumes:
  todo-data-prod:
